Slop support for phrase queries
quickwit-inc/tantivy pull request #1241
Opened 2021-12-26 13:49 UTC by halvorboe

Duplicate of https://github.com/quickwit-inc/tantivy/pull/1110 (because of permissions)

Implements slop for phrase queries (https://github.com/tantivy-search/tantivy/issues/1068).

Currently the phrase query only supports exact matching. The algorithm used does a set intersection between the position of the last term in the phrase and the positions of all the prior terms in the phrase offset by their position in the phrase.

Looked at the Lucene implementation and the description in "Information Retrieval: Implementing and evaluating search engines". 

I modified the current algorithm slightly to keep track of:
- The start of each candidate phrase. Stored in a separate array.
- The first possible end of the phrase. (searching for `a b .` in `a c b d e` it stores the 0 as the start and 1 as the end). There is never any benefit from picking a later instance of the term. This is stored in what was previously called left.

I'll test the efficiency and try to optimize, but the is no change in complexity.

2022-01-03 13:25 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +/// Condition for match is that the value stored in left is less than
```suggestion
/// Condition for match is that the value stored in left is less or equal than
```

2022-01-03 13:31 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +/// resulting array in left.
```suggestion
/// resulting array inline in both `left` and `right`.
```

2022-01-03 13:34 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +        left[i] = right[i];
I'm confused... Why would we fill `left` and `right` , if it is to trash `left` in the end?

2022-01-03 13:35 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +        match left_val.cmp(&right_val) {
The actual three cases are

- `left_val < right - slop`
- `right_slop <= left_val <= right`
- `left_val > right`

2022-01-03 13:37 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +                    if is_temporary {
Once the condition is switch to the ternary choice above, the is_tempory could be avoided with an inner loop.

2022-01-03 13:40 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +        left[i] = right[i];
I think we are only interested in right.
Can't we just write right into left, and keep right non-mutable?

2022-01-03 13:41 UTC, fulmicoton requested changes
See comments inline

2022-01-24 07:52 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
>                  }
```suggestion
            while left_index + 1 < left_len {
```

2022-01-24 07:57 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +         */
```suggestion
        
        // The three conditions are:
        // left_val < right_slop -> left index increment.
        // right_slop <= left_val <= right -> find the best match.
        // left_val > right -> right index increment.
```

2022-01-24 07:57 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +         */
Great comment

2022-01-24 08:08 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +        intersection_len
We are forgetting the last term here.

2022-01-24 08:12 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +        intersection_len
I understand you are trying to be DRY here, but the contract of the `compute_match*` function is horrible.
This makes the code very difficult to understand.

2022-01-24 08:13 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +fn intersection_with_distance(left: &mut [u32], right: &[u32], slop: u32) -> usize {
`intersection_with_slop` maybe?

2022-01-24 08:15 UTC, fulmicoton commented on src/query/phrase_query/phrase_scorer.rs
> +/// resulting array inline in both `left` and `right`.
The result of the `right` array is stored in `left`

2022-03-02 11:22 UTC, halvorboe commented
@fulmicoton Do you have time to take a look?

2022-03-07 06:28 UTC, fulmicoton approved these changes

2022-03-07 06:29 UTC, merged

2022-03-07 06:29 UTC, fulmicoton commented
Thank you @halvorboe