Updated features, benchmark illustration & FAQ.
quickwit-inc/tantivy pull request #1318
Opened 2022-03-18 21:02 UTC by maximkpa

2022-03-19 00:20 UTC, fulmicoton commented
Can we add Pisa to the bench graph?

2022-03-19 15:11 UTC, fmassot commented
> Can we add Pisa to the bench graph?
Does the `global` performance is relevant enough to show it on the chart?

2022-03-21 22:22 UTC, fmassot commented on README.md
> +If you are looking for an alternative to Elasticsearch or Apache Solr, check out [Quickwit](https://github.com/quickwit-oss/quickwit), our search engine built on Tantivy.
```suggestion
If you are looking for an alternative to Elasticsearch or Apache Solr, check out [Quickwit](https://github.com/quickwit-oss/quickwit), our search engine built on top of Tantivy. 
```

2022-03-21 22:24 UTC, fmassot commented on README.md
> +# Companies Using Tantivy
@maximkpa can you add the images in the repository? I don't want to rely on external images.

2022-03-21 22:24 UTC, fmassot commented on README.md
> +- and many more!
```suggestion
```

2022-03-21 22:26 UTC, fmassot commented on README.md
> +- According to our [benchmark](https://tantivy-search.github.io/bench/), Tantivy is approximately 2x faster than Lucene.
```suggestion
- According to our [search latency benchmark](https://tantivy-search.github.io/bench/), Tantivy is approximately 2x faster than Lucene.
```

2022-03-21 22:27 UTC, fmassot requested changes
See comments and remove the unused image.

2022-03-22 17:00 UTC, fmassot commented on README.md
> +- Ruby → [tantiny](https://github.com/baygeldin/tantiny)
```suggestion
- Ruby → [tantiny](https://github.com/baygeldin/tantiny)

You will also find less maintained bindings on [GitHub](https://github.com/search?q=tantivy).
```

2022-03-22 17:01 UTC, fmassot commented on README.md
> +- [lnx](https://github.com/lnx-search/lnx) (An adaptable search engine API)
```suggestion
- [lnx](https://github.com/lnx-search/lnx) (An adaptable search engine API)
- and [more](https://github.com/search?q=tantivy)!
```

2022-03-22 17:02 UTC, fmassot commented on README.md
> +- [seshat](https://github.com/matrix-org/seshat/) (A matrix message database/indexer)
```suggestion
- [seshat](https://github.com/matrix-org/seshat/): A matrix message database/indexer
```

2022-03-22 17:02 UTC, fmassot commented on README.md
> +- [tantiny](https://github.com/baygeldin/tantiny) (Tiny full-text search for Ruby)
```suggestion
- [tantiny](https://github.com/baygeldin/tantiny): Tiny full-text search for Ruby
```

2022-03-22 17:03 UTC, fmassot commented on README.md
> +- [lnx](https://github.com/lnx-search/lnx) (An adaptable search engine API)
```suggestion
- [lnx](https://github.com/lnx-search/lnx): An adaptable search engine API
```

2022-03-22 17:05 UTC, fmassot commented on README.md
> +- [lnx](https://github.com/lnx-search/lnx): An adaptable search engine API
```suggestion
- [lnx](https://github.com/lnx-search/lnx): adaptable, typo tolerant search engine with REST API
```

2022-03-22 17:06 UTC, fmassot approved these changes
Good for me.

2022-03-22 17:06 UTC, fmassot commented
@fulmicoton can you take a final look?

2022-03-22 22:50 UTC, fulmicoton requested changes

2022-03-22 22:50 UTC, fulmicoton commented on README.md
> +<img align="center" src="doc/assets/images/etsy.svg" alt="Etsy" height="25" width="auto" /> &nbsp;
We need to remove Etsy.

2022-03-23 00:57 UTC, fulmicoton commented on README.md
> +<img align="center" src="doc/assets/images/etsy.svg" alt="Etsy" height="25" width="auto" /> &nbsp;
```suggestion
<img align="center" src="doc/assets/images/etsy.svg" alt="Etsy" height="25" width="auto" /> &nbsp;
```

2022-03-23 00:57 UTC, fulmicoton commented on README.md
> +<img align="center" src="doc/assets/images/etsy.svg" alt="Etsy" height="25" width="auto" /> &nbsp;
```suggestion
```

2022-03-23 01:01 UTC, fulmicoton approved these changes

2022-03-23 01:02 UTC, merged