Add aggregation bucket limit
quickwit-inc/tantivy pull request #1363
Opened 2022-05-10 08:33 UTC by PSeitz

Change SegmentCollector.collect to return a `Result`

Validation happens on different phases depending on the aggregation
Term: During segment collection
Histogram: At the end when converting in intermediate buckets (we preallocate empty buckets for the range) Revisit after https://github.com/quickwit-oss/tantivy/issues/1370
Range: When validating the request

Closes #1331

2022-05-16 07:48 UTC, fulmicoton commented on examples/custom_collector.rs
> +        Ok(())
Can you run the bench before and after this change to check it does not impact the compiler perf? 
(Top + Count on "the" term query)

2022-05-16 08:04 UTC, fulmicoton requested changes
I'm scared of the tantivy API change (Collector::collect returning a Result).

If I understand correctly, the goal is to detect that we have reached the collection limit and abort the query.

An alternative could be to detect the excess of buckets, and keep on the collection but avoid adding extra bucket, and return an error when harvesting the segment.
Would that be unreasonable?

2022-05-16 08:10 UTC, PSeitz commented on examples/custom_collector.rs
> +        Ok(())
Yep, but in my benches so far adding `Result` didn't add overhead, except for very tight and simple loops.

E.g. here `let value = self.fast_field_reader.get(doc) as f64;` probably considerably outweighs the Result overhead.

2022-05-17 03:57 UTC, PSeitz commented
> I'm scared of the tantivy API change (Collector::collect returning a Result).
> 
> If I understand correctly, the goal is to detect that we have reached the collection limit and abort the query.

Scared because of performance?

I checked the performance and the "the" TOP10_COUNT query is indeed slower. (TOP_10 and COUNT are the same speed though) I introduced a change which I considered for some time now, which is to collect hits and pass them as block. I need to add a benchmark for the `MultiCollector`, I think this would profit above average from that. Aggregation may also benefit.

In the current change, the collect_block is quite simple implemented, just fowarding to the underlying function, but I with manual unrolling, we could probably gain some more performance.

| Orig  | With Result | With Result collect_block
| ------------- | ------------- |------------- |
|1,632 μs | 1,847 μs +13.2 % | 1,664 μs +2.3 %
|336,574 docs|336,574 docs|336,574 docs

Currently untested which may help is to pass to `collect_block` always a fixed size array of e.g. 64.

Currently we always pass the score, but having some mechanism to only request docs without score could make make some gains on some scenarios.

> 
> An alternative could be to detect the excess of buckets, and keep on the collection but avoid adding extra bucket, and return an error when harvesting the segment. Would that be unreasonable?

I thought about that, but returning a result in collect is the right approach imo, since we could also want to read from other sources than infallible in-memory sources in the segment collection.

2022-05-17 07:38 UTC, fulmicoton commented
> Scared because of performance?

Performance and misuse yes.
I prefer the collect method to not return a Result.

Maybe a bool would do the trick?

COUNT and TOP_10 have a special code path. They are irrelevant here.

2022-05-17 14:34 UTC, PSeitz commented
> 
> Performance and misuse yes. I prefer the collect method to not return a Result.

Misuse how? Every tantivy user should know how to handle `Result`.

> 
> Maybe a bool would do the trick?

Like a C-style API, on false collect the error somewhere? It's likely faster, but also pretty ugly.


I added a bench with the MultiCollector (Count + Top10). It is faster with the collect_block approach.
|  Orig  |  With Result collect_block
| ------------- | ------------- |
|2,275 μs +26.1 % | 1,804 μs
|336,574 docs |  336,574 docs | 

`collect_block` has other potential performance gains, e.g. for TopN we could check upfront if the best score from the block would make it in the TopN, if not skip the whole block. That would probably work pretty well for large results, when the TopN is becoming saturated.

2022-06-23 00:44 UTC, fulmicoton commented on CHANGELOG.md
> +- API Change: `SegmentCollector.collect` changed to return a `Result`.
```suggestion
```

2022-06-23 00:46 UTC, fulmicoton commented on src/aggregation/bucket/range.rs
> +        let buckets: FnvHashMap<SerializedKey, IntermediateRangeBucketEntry> = self
that's super helpful! thanks

2022-06-23 00:48 UTC, fulmicoton approved these changes

2022-06-23 02:27 UTC, merged