Simple faceting implementation for fast numerical fields
quickwit-inc/tantivy pull request #156
Opened 2017-05-15 10:49 UTC by Fiedzia

2017-05-15 11:13 UTC, fulmicoton commented
Thanks. 

Im a bit swamped at the moment but I should have to hit this PR time later this week.

At first glance it looks good.

2017-05-18 13:35 UTC, lnicola commented
Can you extend this to work on `i64` fields?

2017-05-19 11:47 UTC, Fiedzia commented
Done

2017-05-19 12:56 UTC, lnicola commented
Thanks, looks good to me.

You can fix the CI error by running `cargo fmt` with `rustfmt 0.8.4`, but it's no biggie.

2017-05-21 09:09 UTC, lnicola commented
I squashed the commits, rebased against `master` and pusehd to https://github.com/tantivy-search/tantivy/tree/facets.

2017-05-21 12:07 UTC, celaus requested changes
Thanks for the PR, I think it looks good, aside from two minor things 👍

2017-05-21 14:01 UTC, fulmicoton commented
It was merged. Because of some commit squashing I assume, this branch was not automatically closed.

I had to do a bunch of modification for the following reasons.

- `.new()` was not called
- I removed the wrapper that makes it possible to have more than once facet. `tantivy` already has
`chain()` to handle multiple collectors with a static dispatch.
- `set_segment()` was not handled.

Thanks for your PR !

2017-05-21 14:02 UTC, closed without merging

2017-05-22 08:15 UTC, Fiedzia commented on src/collector/facet_collector.rs
> +enum FacedType {
Yes, it's just a typo