prepare fastfield format for null index
quickwit-inc/tantivy pull request #1691
Opened 2022-11-22 14:56 UTC by PSeitz

2022-11-22 17:02 UTC, fulmicoton commented
I don't understand what this PR is about.Can you edit the description? @PSeitz

2022-11-23 02:34 UTC, PSeitz commented
> I don't understand what this PR is about. Can you edit the description and the commit message? @PSeitz

I modified the commit message

2022-11-23 14:39 UTC, fulmicoton requested changes
I don't think this is putting us on the right track for backward compatibility.

Here are the issue I have:
- The footer is constant length.
- It implements stuff for one future that is not there.
- The footer is 11 bytes long and replicated for every column. once we have sparse columns we may end up with a lot of columns. 11 bytes is a bit wasteful (not so terrible but well)

I think we could...
End the fastfield file by a codec version and a magic number.

A codec object would have  a `fn load(&self, data: OwnedBytes) -> Result<_, _>`  instead of the load method in the fastfield_codecs crate.

2022-11-24 03:50 UTC, PSeitz commented
> It implements stuff for one future that is not there.

In just describes the current state, which will be compatible with the future.

> The footer is 11 bytes long and replicated for every column. once we have sparse columns we may end up with a lot of columns. 11 bytes is a bit wasteful (not so terrible but well)

It's 18bytes, that's ~2kb for 100columns, I don't think this will ever be relevant. No problem to change it though.

> I think we could...
> End the fastfield file by a codec version and a magic number.

I think that's a good idea in general and should be added. 

The downside to do that _instead_,  is to introduce a new version and with it all the annoying version handling when one will be fine.



> A codec object would have a fn load(&self, data: OwnedBytes) -> Result<_, _> instead of the load method in the fastfield_codecs crate.

We already have that 
```
fn open_from_bytes(mut data: OwnedBytes, header: NormalizedHeader) -> io::Result<Self::Reader>
```

2022-11-25 11:01 UTC, fulmicoton commented on fastfield_codecs/src/compact_space/mod.rs
> +            // since the to_value also mapps into the same non-mapped spacemich
```suggestion
            // since the to_value also mapps into the same non-mapped space
```

2022-11-27 12:48 UTC, fulmicoton commented on fastfield_codecs/src/null_index_footer.rs
> +        VInt(self.null_index_byte_range.end).serialize(writer)?;
Can you switch to encoding `end-start` instead of `end`

2022-11-28 08:15 UTC, fulmicoton approved these changes

2022-11-28 08:15 UTC, merged