MsQueue to channel
quickwit-inc/tantivy pull request #495
Opened 2019-02-12 21:53 UTC by petr-tik

Implements own Queue using crossbeam-channel. Relies on blocking behaviour of the pop() method

Related to #485 and #491

2019-02-13 23:53 UTC, fulmicoton requested changes

2019-02-13 23:53 UTC, fulmicoton commented on src/core/pool.rs
> +        let elements = vec![1, 2, 3, 4];
There is no need to test for order actually.

2019-02-13 23:53 UTC, fulmicoton commented on src/core/pool.rs
> +    //                 pool.acquire();
The point of this test is to see if the pool behaves correctly when the pool is exhausted.

Right now, your leased item is dropped  right away (before the call to thread::sleep()).
Please fix as follows:

`let _leased_searcher = pool.acquired();`

2019-02-14 19:17 UTC, petr-tik commented
What about RecvError and dealing with Result from .send()?

2019-02-14 22:08 UTC, fulmicoton commented
> What about RecvError and dealing with Result from .send()?

According to doc, they only exist to express that the respective other side of the pipe was dropped.
By design it cannot happen in that pool, so it's ok for you to `panic` on errors.

Just use `.expect()` in both cases.

2019-02-22 00:54 UTC, fulmicoton commented on src/core/pool.rs
> +/// Queue to replace the Michael-Scott Queue, now deprecated in crossbeam
no need for this comment. People don't need to know the history of this queue.

2019-02-22 00:55 UTC, fulmicoton commented on src/core/pool.rs
> +        self.sender.send(elem);
This generates a warning. Make sure you remove all warning at compilation.

2019-02-22 22:00 UTC, petr-tik commented
Rebased onto master and _force_-pushed (sorry). 

thanks for your comments, I addressed them to the best of my ability.

2019-02-23 00:06 UTC, fulmicoton commented
Thanks!

2019-02-23 00:06 UTC, merged