[tantivy] Add brotli codec for row storage
quickwit-inc/tantivy pull request #885
Opened 2020-09-22 19:12 UTC by ppodolsky

Hi, @fulmicoton 

What do you think about it? Until recently I had a Postgres golden copy of all my data that I had been indexing with Tantivy. Tantivy was used only for maintaining inverted index, with any `STORED` fields. Now I've faced with a very hostile environment of limited hard storage, so I would like to try to store all documents in Tantivy `store` and to compress them a little bit stronger than snappy/lz4.

2020-09-25 01:23 UTC, fulmicoton commented
I think this is a good change. Did you test it on your own data to check it was helping?

Let me have a longer look at this PR on Monday. Right now I am in vacation.

2020-09-25 12:05 UTC, ppodolsky commented
I did some measurments, but they are still not finalized.

All tests have bee ndone with all fields are just `STORED`, without indexing. There were 100 000 documents. In the end I have called `wait_merging_threads`. Opt level 3.

```
Brotli 1:  31.51Mb 1.6  secs
Brotli 5:  22.07Mb 3.4  secs
Brotli 7:  22.03Mb 6.4  secs
Brotli 9:  22.00Mb 16.0 secs
Brotli 11: 18.25Mb 35.0 secs
Snappy:     33.70Mb 1.6  secs
```

The same data packed in protobuf, compressed in chunks of size 100 documents by brotli 5 took 21 Mb. Not sure what is the reason, probably this difference is due to presence of skip lists and field type in Tantivy binary format (#887). Or due to slightly different chunkization of data as I split documents by their numbers, not sizes.

I haven't measured decompression yet, but it is told that it is faster than snappy.
I had set set 9 level in this PR and then did measurments. So now I see that 5 level should probably be selected.

2020-10-05 02:12 UTC, fulmicoton commented on src/store/compression_brotli.rs
> +    brotli::BrotliCompress(&mut Cursor::new(uncompressed), compressed, &params)?;
probably not need for cursor here.

2020-10-05 02:17 UTC, fulmicoton commented on src/store/mod.rs
> +compile_error!("feature `lz4` or `brotli` shouldn't be enabled both.");
... "must not be enabled together."

- I am not a native speaker, but I think together is slightly more correct english -unsure I make a load of grammar mistakes-  
- rfc2119 describes what should be our definition of MAY, SHOULD, MUST, SHOULD NOT, MUST NOT in documetnation

2020-10-05 02:18 UTC, fulmicoton requested changes
We probably need to make the compression dynamic. For one thing, it will make it easier to unit test >.<

No need to do anything in this PR however.

2020-10-07 07:00 UTC, ppodolsky commented
If you wish you can create an issue and assign me, I will try to find a time to look at dynamic codec selection as I need it too and fix other notes on the way.

2020-10-08 00:52 UTC, fulmicoton commented
@ppodolsky Can you address the couple of comments in the CR?

2020-10-09 00:53 UTC, fulmicoton requested changes
Can you remove the use of Cursor and fix the comment?

2020-10-09 05:22 UTC, ppodolsky commented
Done, fixed some comments in code on the way.

2020-10-09 05:51 UTC, merged